// <auto-generated />
using System;
using AtmDynamicTerminalListWorker.Entities.Rpa;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AtmDynamicTerminalListWorker.Migrations
{
    [DbContext(typeof(RpaDbContext))]
    [Migration("20210312113411_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AtmDynamicTerminalListWorker.Entities.Rpa.AtmDynamicTerminal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BranchCode");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IPAddress");

                    b.Property<string>("OnlineStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OnlineStatus");

                    b.Property<string>("TerminalBrand")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TerminalBrand");

                    b.Property<string>("TerminalId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TerminalID");

                    b.HasKey("Id");

                    b.ToTable("RPA_ATM_Dynamic_List");
                });

            modelBuilder.Entity("AtmDynamicTerminalListWorker.Entities.Rpa.AtmGL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GL")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATM_GL");

                    b.Property<string>("TerminalId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATM_TerminalID");

                    b.HasKey("Id");

                    b.ToTable("RPA_ATM_GL");
                });
#pragma warning restore 612, 618
        }
    }
}
